project_id = "njorvxodblmvbhhuefmn"

[functions.generate-requirements]
verify_jwt = false

[functions.approve-requirement]
verify_jwt = false

[functions.project-scoping-chat]
verify_jwt = false

[functions.enhance-output]
verify_jwt = false
